export enum TAB {
  PROPERTIES = "PROPERTIES",
  CREATURE = "CREATURE",
  SKILLS = "SKILLS",
  BODYPARTS = "BODYPARTS",
  BOOK = "BOOK",
  SPELLS = "SPELLS",
  CREATELIST = "CREATELIST",
  EMOTES = "EMOTES",
  JSON = "JSON"
}
